blueprint:
  name: ZHA 2x3-tryk TS0046 nrfkrgf4
  description: Automate your Tuya 6-Button Scene Switch using ZHA events. TS0046 nrfkrgf4
  domain: automation
  input:
    tuya_6button_scene_switch:
      name: Tuya 6-Button Scene Switch
      description: Tuya 6-Button Scene Switch to use
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_nrfkrgf4
          model: TS0046
    button_one_short_press:
      name: Single Press
      description: Action to run on button 1 (upper-left) single press
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Double Press
      description: Action to run on button 1 (upper-left) double press
      default: []
      selector:
        action: {}
    button_one_long_press:
      name: Long Press
      description: Action to run on button 1 (upper-left) long press
      default: []
      selector:
         action: {} 
    button_two_short_press:
      name: Single Press
      description: Action to run on button 2 (upper-center) single press
      default: []
      selector:
        action: {}
    button_two_double_press:
      name: Double Press
      description: Action to run on button 2 (upper-center) double press
      default: []
      selector:
        action: {}
    button_two_long_press:
      name: Long Press
      description: Action to run on button 2 (upper-center) long press
      default: []
      selector:
         action: {}  
    button_three_short_press:
      name: Single Press
      description: Action to run on button 3 (upper-right) single press
      default: []
      selector:
        action: {}
    button_three_double_press:
      name: Double Press
      description: Action to run on button 3 (upper-right) double press
      default: []
      selector:
        action: {}
    button_three_long_press:
      name: Long Press
      description: Action to run on button 3 (upper-right) long press
      default: []
      selector:
         action: {} 
    button_four_short_press:
      name: Single Press
      description: Action to run on button 4 (lower-left) single press
      default: []
      selector:
        action: {}
    button_four_double_press:
      name: Double Press
      description: Action to run on button 4 (lower-left) double press
      default: []
      selector:
        action: {}
    button_four_long_press:
      name: Long Press
      description: Action to run on button 4 (lower-left) long press
      default: []
      selector:
         action: {}
    button_five_short_press:
      name: Single Press
      description: Action to run on button 5 (lower-center) single press
      default: []
      selector:
        action: {}
    button_five_double_press:
      name: Double Press
      description: Action to run on button 5 (lower-center) double press
      default: []
      selector:
        action: {}
    button_five_long_press:
      name: Long Press
      description: Action to run on button 5 (lower-center) long press
      default: []
      selector:
         action: {}
    button_six_short_press:
      name: Single Press
      description: Action to run on button 6 (lower-right) single press
      default: []
      selector:
        action: {}
    button_six_double_press:
      name: Double Press
      description: Action to run on button 6 (lower-right) double press
      default: []
      selector:
        action: {}
    button_six_long_press:
      name: Long Press
      description: Action to run on button 6 (lower-right) long press
      default: []
      selector:
         action: {}
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input 'tuya_6button_scene_switch'
action:
- variables:
    command: '{{ trigger.event.data.command }}'   
    endpoint_id: '{{ trigger.event.data.endpoint_id }}'
- choose:
  - conditions: "{{ command == 'remote_button_short_press' }}"
    sequence:
    - choose:
      - conditions: '{{ endpoint_id == 1 }}'
        sequence: !input 'button_one_short_press'
      - conditions: '{{ endpoint_id == 2 }}'
        sequence: !input 'button_two_short_press'
      - conditions: '{{ endpoint_id == 3 }}'
        sequence: !input 'button_three_short_press'
      - conditions: '{{ endpoint_id == 4 }}'
        sequence: !input 'button_four_short_press'
      - conditions: '{{ endpoint_id == 5 }}'
        sequence: !input 'button_five_short_press'
      - conditions: '{{ endpoint_id == 6 }}'
        sequence: !input 'button_six_short_press'
  - conditions: "{{ command == 'remote_button_double_press' }}"
    sequence:
    - choose:
      - conditions: '{{ endpoint_id == 1 }}'
        sequence: !input 'button_one_double_press'
      - conditions: '{{ endpoint_id == 2 }}'
        sequence: !input 'button_two_double_press'
      - conditions: '{{ endpoint_id == 3 }}'
        sequence: !input 'button_three_double_press'
      - conditions: '{{ endpoint_id == 4 }}'
        sequence: !input 'button_four_double_press'
      - conditions: '{{ endpoint_id == 5 }}'
        sequence: !input 'button_five_double_press'
      - conditions: '{{ endpoint_id == 6 }}'
        sequence: !input 'button_six_double_press'
  - conditions: "{{ command == 'remote_button_long_press' }}"
    sequence:
    - choose:
      - conditions: '{{ endpoint_id == 1 }}'
        sequence: !input 'button_one_long_press'
      - conditions: '{{ endpoint_id == 2 }}'
        sequence: !input 'button_two_long_press'
      - conditions: '{{ endpoint_id == 3 }}'
        sequence: !input 'button_three_long_press'
      - conditions: '{{ endpoint_id == 4 }}'
        sequence: !input 'button_four_long_press'
      - conditions: '{{ endpoint_id == 5 }}'
        sequence: !input 'button_five_long_press'
      - conditions: '{{ endpoint_id == 6 }}'
        sequence: !input 'button_six_long_press'